### ISSUE TITLE
RuntimeError: HiGHS solution status could not be retrieved

### ISSUE THREAD

**Issue by ishankholkar** [TUMCREATE-ESTL/FLEDGE.jl#25]
Hello sir,

Hope you are doing well.

I have followed the installation guidelines and installed after cloning the package.

When i run any of the given examples in the repository, i get the below error. Request you to kindly help me resolve the error.

Thank you...
----------------------------------------------------------------------------
(base) C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo>conda activate mesmo

(mesmo) C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo>"C:/Users/Ishan Kholkar/anaconda3/envs/mesmo/python.exe" "c:/Users/Ishan Kholkar/Desktop/smartgrid/mesmo/examples/tutorial/example_3.py"
  File "C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\mesmo\solutions.py", line 1218, in solve_highs
    status = next(line for line in output if line.startswith("Model   status      : "))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Ishan Kholkar/Desktop/smartgrid/mesmo/examples/tutorial/example_3.py", line 54, in <module>
    main()
  File "c:/Users/Ishan Kholkar/Desktop/smartgrid/mesmo/examples/tutorial/example_3.py", line 45, in main
    optimization_problem.solve()
  File "C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\mesmo\solutions.py", line 1054, in solve
    self.solve_highs()
  File "C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\mesmo\solutions.py", line 1221, in solve_highs
    raise RuntimeError(f"HiGHS solution status could not be retrieved:\n{command}\n{''.join(output)}")
RuntimeError: HiGHS solution status could not be retrieved:
C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\highs\bin\highs --model_file C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\results\temp_2022-10-11_17-30-49_318556\problem.mps --options_file C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\results\temp_2022-10-11_17-30-49_318556\options.txt --solution_file C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo\results\temp_2022-10-11_17-30-49_318556\solution.txt
'C:\Users\Ishan' is not recognized as an internal or external command,
operable program or batch file.

(mesmo) C:\Users\Ishan Kholkar\Desktop\smartgrid\mesmo>

**Comment by stroitzsch** [comment]
Hi there, just picking up the work here.

Is this still an issue & should I look into it, or is it out of date?
